### ISSUE TITLE
httpie config.json assumes EdgeGrid auth, breaking other requests

### ISSUE THREAD

**Issue by stuartio** [akamai/akamai-docker#27]
Maybe best to remove the --auth-type=edgegrid option to make it more flexible for non {OPEN} api commands @ynohat

**Comment by ynohat** [comment]
@lukaszczerpak @javiergarza I'd like to consult you on this before proceeding.

Currently the httpie config is hardcoded to use edgegrid auth, and you can override by explicitly adding `-A otherauth`.

The issue is that if you simply want to make a request without auth, you are stuck with adding some dummy authentication options because httpie does not allow something like `-A noauth`.

The assumption was that people would use httpie for edgegrid because of the integration, but could use e.g. curl for anything else. I agree with @stuartio that this is the wrong tradeoff, and people should be able to use httpie in place of curl for ad hoc requests.

WDYT?

**Comment by lukaszczerpak** [comment]
Timeout and theme can stay in the config file, but authtype should be removed.
IMHO it's not so breaking change as the old unofficial docker image didn't enforce edgegrid authtype and frankly I was always specifying authtype when using the new image.

**Comment by javiergarza** [comment]
I agree, I personally use HTTPie for making calls with other auth methods and prefer not to have edgegrid hardcoded in the config file to avoid errors (I use an alias instead for Akamai specific calls). 

@ynohat / @lukaszczerpak does one of you wants to go ahead and update the config file? (otherwise I will try to do it later today or tomorrow)
