### ISSUE TITLE
Support for terraform 0.13

### ISSUE THREAD

**Issue by javiergarza** [akamai/akamai-docker#29]
Hashicorp released [Terraform 0.13](https://github.com/hashicorp/terraform/releases) on August 10.  
@ynohat do you know if we just need to update the variables below on the [Dockerfile](https://github.com/akamai/akamai-docker/blob/master/dockerfiles/terraform.Dockerfile) or do we need anything else to support the new TF version?
```
ARG TERRAFORM_VERSION=0.12.20
ARG TERRAFORM_SHA256SUM=46bd906f8cb9bbb871905ecb23ae7344af8017d214d735fbb6d6c8e0feb20ff3
```

**Comment by zstlaw** [comment]
Also I didn't see where you specify the provider to pull down but in 0.13 the way to specify the provider has changed.  In addition to the provider block there is a new required_providers block in terraform and the source has changed from terraform-providers/akamai to akamai/akamai.  Example

```terraform {
 required_providers {
   akamai = {
     source = "akamai/akamai"
   }
 }
 required_version = ">= 0.13"
}
```

**Comment by ynohat** [comment]
Thanks for that @zstlaw, I saw something to this effect in the release notes, but I haven't had time to fully parse them yet and understand whether we could painlessly upgrade the image, in answer to @javiergarza's question.

We will indeed need to update at least [this line](https://github.com/akamai/akamai-docker/blob/master/dockerfiles/terraform.Dockerfile#L53) to match the new provider syntax, in addition to the variables mentioned above.

Do we want to do this? My concern is forcing users to use 0.13 just because they downloaded the latest image, will force them to upgrade all their configs. They'll likely not want that?

**Comment by lukaszczerpak** [comment]
What about keeping 0.12.x in prod and upgrade to 0.13.x in dev branch? At 
least for 1-2 image release cycles, unless we see higher demand to upgrade 
in prod?

--
pozdrawiam,
Łukasz Czerpak

W 19 sierpnia 2020 16:39:25 Anthony Hogg <notifications@github.com> napisał:

**Comment by ynohat** [comment]
I propose making this change after #33 and translate this as a major version increment to reflect the breaking change semantics.

**Comment by ynohat** [comment]
This is done
