### ISSUE TITLE
cloudlets command does not recognize --section option

### ISSUE THREAD

**Issue by brucep-care** [akamai/akamai-docker#69]
Most commands recognize `--section`, for example:

    $ akamai --section default purge invalidate --tag foo
    ...
    Purging...
    Purging...... [OK]

The cloudlet command, however, does not:

    $ akamai --section default cloudlets list
    ...
    Usage: akamai cloudlets list [OPTIONS]
    Try 'akamai cloudlets list -h' for help.
    
    Error: no such option: --section

The only way I can get the `cloudlets` command to work is to add a `[cloudlets]` section to my .edgerc file. Since I use the same API credentials for all my Akamai work I prefer to alias the `akamai` command to include `--section default` rather than having a dozen entries in .edgerc that all contain the exact same credentials for each command I may use...

**Comment by securitylevelup** [comment]
Thanks for reporting this issue. On inspection, it seems that the cli-cloudlets package does not have the option to specify edgerc section yet. 

Adding the specific cloudlets section to the edgerc is the only workaround right now.

I will ask the team that manages the cli-cloudlets package to add the section option to the next release. 

The akamai-docker pulls in the latest version of the Akamai CLI as well as the individual packages such as cli-cloudlets so while this issue is of course also present in the akamai-docker, it is actually a cli-cloudlets issue.

**Comment by aetsai** [comment]
Have you tried to see if this works?
akamai cloudlets --section default list

**Comment by lkowalsk-akamai-com** [comment]
@brucep-care  as mentioned above, looks like you are using wrong order of parameters, see here as well: https://github.com/akamai/cli-cloudlets#global-flags
